sudo: required

language: c

services:
  - docker

before_script:
  - docker build --tag devel -f Dockerfile.dev .

script:
  - docker create --name develcontainer devel
  - mkdir Genbank
  - docker cp develcontainer:/source/dist-newstyle/build/x86_64-linux/ghc-8.6.5/Genbank-2.0.0/x/GenbankConverter/build/GenbankConverter/GenbankConverter Genbank
  - docker cp develcontainer:/source/dist-newstyle/build/x86_64-linux/ghc-8.6.5/Genbank-1.8.0/x/GenbankSequenceExtractor/build/GenbankSequenceExtractor/GenbankSequenceExtractor Genbank
  - cp LICENSE Genbank
  - tar -cvzf Genbank.tar.gz Genbank


deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: "Genbank.tar.gz"
  on:
    tags: true
